---
- name: DevOps Platform Health Check
  hosts: k3s_cluster
  gather_facts: yes
  tasks:
    - name: Check system uptime
      command: uptime
      register: uptime_result
    
    - name: Check disk usage
      shell: df -h / | tail -1 | awk '{print $5}'
      register: disk_usage
    
    - name: Check memory usage
      shell: free -m | grep Mem | awk '{printf "%.0f", $3/$2 * 100}'
      register: mem_usage
    
    - name: Check CPU load
      shell: uptime | awk -F'load average:' '{print $2}' | awk '{print $1}'
      register: cpu_load
    
    - name: Display results
      debug:
        msg:
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - "Host: {{ inventory_hostname }}"
          - "Uptime: {{ uptime_result.stdout }}"
          - "Disk Usage: {{ disk_usage.stdout }}"
          - "Memory Usage: {{ mem_usage.stdout }}%"
          - "CPU Load: {{ cpu_load.stdout }}"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
